requires 'Plack', '>= 1.0047';
requires 'Starman', '>= 0.4014';
requires 'CGI';
requires 'CGI::Simple';
requires 'CGI::Session';
requires 'DBI';
requires 'DBD::SQLite';
requires 'Template';
requires 'Crypt::URandom';
requires 'Digest::SHA';
requires 'MIME::Base64';
requires 'Plack::Request';
requires 'Text::Trim';
requires 'Plack::Builder';
requires 'Plack::Middleware::Header';
requires 'Plack::Loader';
requires 'Plack::Session';
requires 'Devel::hdb';
requires 'Test::More';
requires 'Test::Exception';
#requires 'Test::BDD::Cucumber::Load';
requires 'Test::BDD::Cucumber::StepFile';
requires 'Plack::Middleware::CSRFBlock';
